name: Lighthouse CI

on:
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Start server
        run: pnpm start &
        env:
          PORT: 3000

      - name: Wait for server
        run: pnpm dlx wait-on http://localhost:3000

      - name: Run Lighthouse CI (Mobile)
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:3000/en
            http://localhost:3000/en/resources
          configPath: "./lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Run Lighthouse CI (Desktop)
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:3000/en
            http://localhost:3000/en/resources
          configPath: "./lighthouserc-desktop.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
